### PR TITLE
Login register pages

### PR DESCRIPTION
**Pull request by Rolguard**
Contains some basic functionality, layout draft completed but still more room for visual updates or refactoring.
Successful register sends a post request to backend but login does not send any HTTP request as code for handling and generating tokens is currently unknown.

### CODE REVIEW

**Comment by Suchpuns** [comment]
image
Shouldn't show the password (make it dots instead).

image
also shouldn't autofill in the password field.
Should check this out:
https://stackoverflow.com/questions/45201351/masking-password-input-in-reactjs

**Review by Suchpuns — CHANGES_REQUESTED** [review]
image
Shouldn't show the password (make it dots instead).

image
also shouldn't autofill in the password field.
Should check this out:
https://stackoverflow.com/questions/45201351/masking-password-input-in-reactjs

**Comment by Rolguard** [comment]
> image Shouldn't show the password (make it dots instead).
> 
> image also shouldn't autofill in the password field. Should check this out: https://stackoverflow.com/questions/45201351/masking-password-input-in-reactjs

Addressed requested changes for password visibility and disabling autocomplete in latest commit, please review again.

**Review by Suchpuns — APPROVED** [review]
LGTM!

**Pull request merged**
